/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kc_genid_CONSTANTS_H
#define kc_genid_CONSTANTS_H

#include "kc_genid_types.h"

namespace KC_GenID {

class kc_genidConstants {
 public:
  kc_genidConstants();

};

extern const kc_genidConstants g_kc_genid_constants;

} // namespace

#endif
