/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kc_genid_constants.h"

namespace KC_GenID {

const kc_genidConstants g_kc_genid_constants;

kc_genidConstants::kc_genidConstants() {
}

} // namespace

